# Generated by Django 5.2.6 on 2025-09-28 19:39

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postuserlikes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[\\w\\s]+$', 'Title must be alphanumeric.')]),
        ),
        migrations.AlterField(
            model_name='postuserlikes',
            name='like_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=7),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='postuserlikes',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_user_post_like'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_tag_name_ci'),
        ),
    ]
